name: Release

on:
  push:
    tags: 
      - 'v*'

env:
  CARGO_TERM_COLOR: always
  SCCACHE_GHA_ENABLED: "true"
  RUSTC_WRAPPER: "sccache"

permissions:
  contents: write
  
jobs:
  build-binary:
    runs-on: ubuntu-latest
    name: Build
    steps:
      - name: Check out repository
        uses: actions/checkout@v3
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: nightly
      - name: Run sccache-cache
        uses: mozilla-actions/sccache-action@v0.0.3
      - name: Build binary
        uses: actions-rs/cargo@v1
        with:
          command: build
          args: --release
      - uses: actions/upload-artifact@master
        with:
          name: action-ask-bard
          path: target/release/action-ask-bard
  release-binary:
    name: Release
    needs: build-binary
    runs-on: ubuntu-latest
    steps:
      - name: download productions
        uses: actions/download-artifact@master
        with:
          name: action-ask-bard
          path: .
      - name: Release
        uses: softprops/action-gh-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          files: action-ask-bard

